print('Vamos analisar.')
a = input('Escreva uma palavra: ')
print(f'O tipo primitivo é {type(a)}')
print(f'Tem espaço: {a.isspace()}')
print(f'É um número: {a.isnumeric()}')
print(f'É alphabetico: {a.isalpha()}')
print(f'É alphanumérico: {a.isalnum()}')
print(f'É maiuscula: {a.isupper()}')
print(f'É minuscula: {a.islower()}')
print(f'Está capitalizado: {a.istitle()}')
